### PR TITLE
add stack.yaml

### PR DESCRIPTION
**Pull request by joehillen**

### CODE REVIEW

**Comment by fosskers** [comment]
Have you built aura with stack? If so, what's the experience like?

**Comment by joehillen** [comment]
@fosskers Yes, [stack](https://github.com/commercialhaskell/stack) is 100x better than `cabal-install`. Try it out. I'll probably never use `cabal-install` ever again.

**Comment by joehillen** [comment]
Still waiting on travis to add support for stack. I have no idea what the hold up is. https://github.com/travis-ci/apt-package-whitelist/issues/379

**Comment by fosskers** [comment]
What's been your experience using it, more specifically? I'd like more 1st-hand accounts from happy people before I attempt a switch.

**Comment by joehillen** [comment]
You can use both side-by-side. They don't conflict.

```
sudo aura -A haskell-stack
stack setup # only need to run once to download ghc
stack build
```
beyond that is has a ton of awesome features. `cabal-install` has always been a giant mess and it's not worth clinging to.

**Comment by bb010g** [comment]
:+1: for building with `stack`. Using it for a new project and it's working great.

**Comment by fosskers** [comment]
Which GHC is it? We need at least 7.10.

**Comment by joehillen** [comment]
[lts-3.1](https://www.stackage.org/lts-3.1) is 7.10.2

**Comment by fosskers** [comment]
@bb010g So long as I can get `haskell-mode` to work with stack, I'd be willing to switch. That said, I don't actually mind sandboxes, except having unnecessary duplicates of large libraries sometimes.

**Comment by joehillen** [comment]
@fosskers Here is my [haskell-mode-init.el](https://gist.github.com/joehillen/47899db33bdf632a9788) if that helps.

**Comment by fosskers** [comment]
Thanks, I'll see if I can get that going.

**Pull request merged**
