### PR TITLE
Escape urls for the AUR

### LINKED ISSUE #421: Bad handling of packages with the '+' character in their name
# Bug details
Aura reports that the AUR package [`gimp-plugin-separate+`](https://aur.archlinux.org/packages/gimp-plugin-separate%2B/) does not exist:

```shell
% pacman -A gimp-plugin-separate+
aura >>= The following are not AUR packages:
gimp-plugin-separate+
```

I noticed that the `+` is url encoded in the AUR url so I tried entering the url encoded package name and it does then recognise it:

```shell
% pacman -A gimp-plugin-separate%2B
aura >>= Determining dependencies...
aura >>= AUR Packages:
gimp-plugin-separate%2B

aura >>= Continue? [Y/n] Y
```

But unfortunately, the build immediately fails:
```shell
...
aura >>= Building `gimp-plugin-separate%2B`...
aura >>= Well, building `gimp-plugin-separate%2B` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
aura >>= Failed to obtain build scripts for `gimp-plugin-separate%2B`.
aura >>= Would you like to continue anyway? [Y/n] n
aura >>= Building failed.
```

# Expected behaviour
```shell
% pacman -A gimp-plugin-separate+
aura >>= Determining dependencies...
aura >>= AUR Packages:
gimp-plugin-separate+

aura >>= Continue? [Y/n] Y
```

# Notes
- I can't recall ever coming across another package with a `+` in it before. _Update:_ just had a look in the AUR and there's actually quite a few.
- I haven't looked at the code but I guess it could be trying to hit the AUR with a double encoded package name which is causing it to fail.
- I was able to manually download the PKGBUILD, build & install fine

# System info
```shell
% uname -a
Linux h4lfwit 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

% alias pacman
pacman='sudo aura'

% pacman --version
 __ _ _  _ _ _ __ _    Pacman v5.0.1 - libalpm v10.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2016 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.3.6     
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
```

### PR DESCRIPTION
**Pull request by theotherjimmy**
should resolve #421

### CODE REVIEW

**Comment by theotherjimmy** [comment]
@bb010g, could you review?

**Comment by theotherjimmy** [comment]
@willfrew, could you test?

**Comment by fosskers** [comment]
Wreq wasn't handling that automatically?

**Comment by theotherjimmy** [comment]
nope. Strange.

**Comment by theotherjimmy** [comment]
@fosskers, CI done. Want to merge?

**Comment by fosskers** [comment]
Ah, I see. We're only grabbing PKGBUILDs the old way via wreq, and all other RPC calls are via `servant` in the `aur` library.

**Comment by fosskers** [comment]
Thanks for this, guys.

**Comment by willfrew** [comment]
Legend(s) - cheers :)

**Pull request merged**
