### PR TITLE
Updated Spanish language

### PR DESCRIPTION
**Pull request by PandaFoss**
I have updated most of the lines to Spanish. On the end of the file there are some that are only in English, should they also be translated?

### CODE REVIEW

**Comment by fosskers** [comment]
Thank you for this! Yes, please add translations whereever they're missing.

**Comment by PandaFoss** [comment]
I think I have finished the Spanish translation of all the lines.
I have an other question. In the `Languages.hs` file, on line 1359 I think it is necessary to add `\case` to the end of the line, in order to add the translations, am I correct?

**Comment by fosskers** [comment]
Which function name, specifically? `provides_1`? Then yes, You'd need the `\case` before pattern matching as is done in the other functions.

**Comment by PandaFoss** [comment]
I add it?

**Comment by fosskers** [comment]
Yes please :)

**Comment by PandaFoss** [comment]
Hmm, there was a problem on the last checkup but I'm not sure...

**Comment by fosskers** [comment]
It's okay, I'll fix it and merge it manually. Thank you!

**Comment by fosskers** [comment]
Thanks again!

**Pull request merged**
