### PR TITLE
[Aura 1.4] Multiple fixes, updates from master

### PR DESCRIPTION
**Pull request by theotherjimmy**
pulled in the haskell-aur updates and fixed some of my bugs introduced by missuse of shelly. You should be able to build and install.

### CODE REVIEW

**Comment by fosskers** [comment]
Travis seems to be puking?

**Comment by theotherjimmy** [comment]
It's the 01-01-16 resolver. It's missing some deps.

**Comment by fosskers** [comment]
You can remove that resolver from the travis config, then.

**Comment by theotherjimmy** [comment]
Should be stable and look like the old aura in output now.

**Comment by fosskers** [comment]
Minor bug with non-verbose output. The green colour from the `...` after the name of the package being currently built spills over onto the `makepkg` output. Can you confirm?

**Comment by theotherjimmy** [comment]
yeah, that happens.

**Comment by fosskers** [comment]
Should be auto-fix once we change how colouring works via `extensible-effects`. LGTM

**Pull request merged**
