### PR TITLE
Added logo in SVG.

### PR DESCRIPTION
**Pull request by Anton-Latukha**

### CODE REVIEW

**Comment by fosskers** [comment]
Awesome, thank you! We should use this where ever we can.

**Comment by bb010g** [comment]
Would it be possible to keep the yellow / gray / dark gray color scheme currently used? The blue eye feels jarring against the yellow, and the old gray logo colors fit better with a gray eye.

**Comment by Anton-Latukha** [comment]
A coloring of the ready picture is very simple in Inkscape.
Haskell logo is grouped, ungroup and change filling colors.
I leave further coloring up to project.

**Comment by bb010g** [comment]
We're going to see about redoing this.

**Pull request closed without merging**
