### PR TITLE
Uses fused-effects instead of freer-simple

### PR DESCRIPTION
**Pull request by jkachmar**
What it says on the tin above, this is pretty much a rote translation from `freer-simple` to `fused-effects`.

I tried to riff off of robrix/fused-effects#82 a bit for the `sendM` thing, but I'm still having some trouble getting it to work with `MonadIO` rather than plain ol' `IO`.

I don't have Arch installed and haven't gotten to setting up a Docker image to let me thoroughly test and profile the executable in.

### CODE REVIEW

**Comment by fosskers** [comment]
[These are some nice numbers.](https://github.com/patrickt/effects-benchmarks) I will get this merged.

**Comment by jkachmar** [comment]
This is a bit out of date; when I get home tonight I’ll see about targeting the latest `fused-effects` and cleaning it up.

**Comment by fosskers** [comment]
Thanks man :+1:

**Comment by fosskers** [comment]
Note on the `package.yaml` conflict: I've dropped usage of those files and gone back to `.cabal` files for each of the subprojects here.

**Comment by jkachmar** [comment]
I've added `fused-effects-0.4.0.0` as an extra dependency, since it's got all the updated goodies, rebased off of develop, and chased down all the type errors.

As a small stylistic change I've used explicit imports for all the effects, even though `Control.Effect` re-exports a lot, just so it's easier to track what comes from which module.

**Comment by fosskers** [comment]
Thank you!!

**Comment by jkachmar** [comment]
I’ll have to check tomorrow, but I think the `pPrintNoColor` workaround I added isn’t necessary anymore (given that `Lift` has a `MonadUnliftIO` instance).

If you get around to merging this beforehand I can open a very small PR afterwards, otherwise I’ll just update it here :)

**Comment by fosskers** [comment]
I'll need another day or two to get around to finishing #530 .

**Comment by fosskers** [comment]
... I merged #530 and broke everything here, but the looks of it! :sweat_smile:

**Comment by jkachmar** [comment]
Okay, that was waaaaaaaaay more annoying that I thought it was going to be.

It compiles locally, but there's always the chance that I messed up something when merging and translating the type sigs to be `fused-effects`-friendly, so one more review would probably be helpful.

**Comment by fosskers** [comment]
I'll be double-checking all of it :) Thank you, my friend.

**Comment by fosskers** [comment]
Just merged another big thing (sorry). I'll take this over, fix up the conflicts, and then get some perf numbers.

**Comment by fosskers** [comment]
Aaaand done!

**Comment by jkachmar** [comment]
🎉 thanks for the merge!

Did you get a chance to take perf numbers, and if so how do they look?

**Comment by fosskers** [comment]
I didn't bother generating a flame graph, but I did my usual timing of dependency resolution of `ros-lunar-desktop`, which one of the biggest dep graphs on the entire AUR. Resolution speed didn't slow down at all with this PR (and everything still works).

**Comment by fosskers** [comment]
I'll be doing a release soon, so that this work is included in an official release.

**Pull request merged**
