### PR TITLE
Update spanish translation.

### PR DESCRIPTION
**Pull request by skgsergio**
Work done in this PR:
- Translate missing strings.
- Update strings that its original string changed at some point.
- Change some wording to be consistent in all the strings.

Not sure if I have to PR to master, if I have to change something please just answer this PR and I will fix it ASAP.

### CODE REVIEW

**Comment by skgsergio** [comment]
Had to add a fix, I forgot to change the pattern match leaving two "German" matches in a string: https://travis-ci.org/aurapm/aura/jobs/99586355#L610

Sorry :(

**Comment by fosskers** [comment]
Looks good to me. Thanks for this.

Anything else you want to add before I merge?

**Comment by skgsergio** [comment]
Nope, its all :)

**Comment by fosskers** [comment]
Awesome, thanks.

**Pull request merged**
