### PR TITLE
Update Portuguese translation

### PR DESCRIPTION
**Pull request by wamaral**
Included some missing translations, and fixed some that were not very precise

Since it's only a few changes, I didn't include my name in the list. Feel free to do so if you'd like, though

### CODE REVIEW

**Comment by fosskers** [comment]
Thank you! Actually, Aura is undergoing a massive overhaul. Can you target this to the `aura-1.5` branch to make sure everything is correct?

**Comment by wamaral** [comment]
Yeah, sure! I'll fix it real quick

**Comment by wamaral** [comment]
Done :)

**Comment by fosskers** [comment]
Awesome :sunglasses: I'll merge this on Monday (24 hours from now or so).

**Comment by fosskers** [comment]
Thanks again for these.

**Pull request merged**
