### PR TITLE
Multiple bug fixes

### LINKED ISSUE #340: Cannot decode byte
I am getting the following error when installing/upgrading some AUR packages with the new aura 1.3.2.0:
`aura: Cannot decode byte '\x6e': Data.Text.Internal.Encoding.streamDecodeUtf8With: Invalid UTF-8 stream`

Any ideas?

### LINKED ISSUE #391: Building `muttprint` results in invalid argument error
When attempting to build [muttprint](https://aur.archlinux.org/packages/muttprint) I get the following error:

```
-- aura: fd:9: hGetContents: invalid argument (invalid byte sequence)
```

My locale is:

```
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

### LINKED ISSUE #392: Collect stdout/stderr using ByteStrings
See #391 

More locale issues here.

### LINKED ISSUE #398: Dependency could not be found
`python2-joe` updated recently, and now requires `python2-git`.

`aura` cannot find the dependency, although `aura -As python2-git` lists it at the top.

Trying to get information `aura -Ai python2-git` returns a `aura: Maybe.fromJust: Nothing`

Searching for similar issues suggests that the PKGBUILD doesn't exists. However it does and it looks ok.

### LINKED ISSUE #410: Failed to automatically install builddeps.
I tried to update via -Aux, and got this:

```
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
gnome-chemistry-utils : 0.14.10-1 => 0.14.12-1

aura >>= Determining dependencies...
aura >>= AUR Packages:
gnome-chemistry-utils

aura >>= Continue? [Y/n] 
aura >>= Building `gnome-chemistry-utils`...
==> Making package: gnome-chemistry-utils 0.14.12-1 (Sat Apr  9 04:05:22 IDT 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> intltool
  -> xulrunner
  -> npapi-sdk
==> ERROR: Could not resolve all dependencies.
aura >>= Well, building `gnome-chemistry-utils` failed.
```

All three packages are regular arch ones; -S --asdeps on them solved the issue.

### LINKED ISSUE #427: Failed `aura -Au` -- Prelude.read: no parse
#408 was closed with reason it has fixed in 1.3.7, so I updated and now I get this at the end:

```
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
    2gis : 3.15.10.0-1 => 3.16.3.0-1
    aarchup : 1.7.3-2 => 1.8.1-1
    alsaequal : 0.6-12 => 0.6-14
    byobu : 5.104-1 => 5.108-1
    cargo-bin : 20160119-1 => 20160517-1
    copyq-git : 20141026-1 => 20151130-1
    cppreference-qt : 20150808-1 => 20151129-1
    dbvis : 9.2.13-1 => 9.5.3-1
    decklink-sdk : 1:10.1.4-1 => 1:10.5-1
    eclipse-checkstyle : 6.5.0-1 => 6.19.1-1
    eiskaltdcpp-core-git : 2.3.0.4848.d06b149-1 => 2.3.0.4958.52af555-1
    eiskaltdcpp-daemon-git : 2.3.0.4848.d06b149-1 => 2.3.0.4958.52af555-1
    eiskaltdcpp-data-git : 2.3.0.4848.d06b149-1 => 2.3.0.4958.52af555-1
    eiskaltdcpp-gtk-git : 2.3.0.4848.d06b149-1 => 2.3.0.4958.52af555-1
    eiskaltdcpp-qt-git : 2.3.0.4848.d06b149-1 => 2.3.0.4958.52af555-1
    epsxe : 1.9.25-8 => 2.0.5-4
    freshplayerplugin : 0.3.5-2 => 0.3.6-1
    gtk-theme-arc : 20160331-1 => 20161005-1
    hunspell-ru : 20131101-1 => 20131101-2
    inox-bin : 48.0.2564.82-1 => 53.0.2785.101-1
    intellij-idea-ce-eap : 3:16.144.3891.8-1 => 2016.3.163.6512.17-1
    j4status-plugins-git : 30.98a8146-1 => 40.801300f-1
    jdk : 8u77-1 => 8u112-1
    jetty : 9.3.6-1 => 9.3.11-1
    jitsi : 2.8.5426-2 => 2.8.5426-3
    jmk-x11-fonts : 3.0-1 => 3.0-2
    jre : 8u77-1 => 8u112-1
    jreen : 1.2.0-1 => 1.2.1-1
    lib32-libtinfo : 6-7 => 6-9
    libbs2b : 3.1.0-2 => 3.1.0-4
    libnatspec : 0.2.6-1 => 0.3.0-2
    libqtxdg-git : 1.1.0.29.g641754a-1 => 1.2.0.13.gab0f65c-1
    libqxt : 0.6.2-4 => 0.6.2-5
    linthesia : 0.4.3-3 => 0.4.3-5
    lximage-qt : 0.5.0-1 => 0.5.0-3
    megatools : 1.9.95-3 => 1.9.97-1
    mpdas : 0.4.1-1 => 0.4.2-1
    ncurses5-compat-libs : 6.0-2 => 6.0-4
    otf-font-awesome : 4.3.0-2 => 4.6.3-1
    packettracer : 6.2-2 => 7.0-2
    pamixer-git : 20121122-3 => 20150209-1
    popcorntime-git : r5144.6444037-1 => r5925.1e2f946-2
    profanity-git : 2827.8e46b9e-1 => 4737.d485588-1
    psi-plus-git : 0.16.457-1 => 0.16.559.574-1
    psi-plus-l10n-git : 0.16.441.2-1 => 0.16.457-1
    psi-plus-plugins-git : 0.15.443-1 => 0.15.476-1
    pybitmessage-git : 0.4.4.r3.gced463b-1 => 0.6.0.r1.gaf0dfdc-1
    pycharm-community-eap : 5.0.0.143.24-2 => 2016.2.162.1236.15-1
    pyqt-doc : 5.4.2-1 => 5.7-3
    python-aiodns : 1.0.0-1 => 1.1.1-1
    python-plotly : 1.6.12.r773.gd88c5d0-1 => 1.12.9-1
    python-slixmpp : 1.1-1 => 1.2.1-1
    python-slixmpp-git : r1796.62eefdb-1 => r2046.bb81fbb-1
    python-tomate : 0.4.1-1 => 0.6.0-1
    python-wiring : 0.2.4-1 => 0.3.0-1
    qtermwidget-git : 0.6.0.46.g0e50464-1 => 0.6.0.48.g10e1796-1
    qtkeychain-qt4 : 0.5-2 => 0.6.1-1
    qxkb : 0.4.6-2 => 0.4.6-3
    recstudio : 4.0_20130724-1 => 4.1_20150924-1
    retroshare : 0.5.5c-2 => 0.6.1-1
    rtmidi : 2.1.0-3 => 2.1.1-1
    signify : 8-1 => 18-1
    skype : 4.3.0.37-7 => 4.3.0.37-8
    teamviewer : 11.0.52520-1.5 => 11.0.67687-4
    thermald : 1.4.3-1 => 1.5.4-1
    tomate-gtk : 0.4.0-1 => 0.6.0-1
    unzip-natspec : 6.0-5 => 6.0-6
    vim-toml-git : 20141015-1 => 20150403-1
    wrk : 4.0.1-1 => 4.0.2-1

aura >>= The following are not AUR packages:
    eiskaltdcpp-core-git
    eiskaltdcpp-daemon-git
    eiskaltdcpp-data-git
    eiskaltdcpp-gtk-git
    eiskaltdcpp-qt-git

aura >>= Determining dependencies...
aura: Prelude.read: no parse
```

### LINKED ISSUE #433: Cannot install streamlink-git?
````
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
streamlink-git : 0.3.1.r8.gde54399-1 => 0.3.1.r13.g9df6196-1

aura >>= `streamlink-git` PKGBUILD changes:
--- a/streamlink-git/PKGBUILD
+++ b/streamlink-git/PKGBUILD
@@ -1,15 +1,15 @@
 # Maintainer: Josip Ponjavic <josipponjavic at gmail dot com>
 
 pkgname=streamlink-git
-pkgver=0.3.1.r0.g2c34781
+pkgver=0.3.1.r13.g9df6196
 pkgrel=1
 pkgdesc='CLI program that launches streams from various streaming services in a custom video player (livestreamer fork)'
 arch=('any')
 url='https://streamlink.github.io/'
 license=('BSD')
-depends=('python-iso3166' 'python-iso639' 'python-pycryptodome' 'python-requests' 'rtmpdump')
-checkdepends=('python-mock' 'python-pytest')
-makedepends=('git' 'python-setuptools' 'python-sphinx')
+depends=("python-"{iso3166,iso639,pycryptodome,requests} 'rtmpdump')
+checkdepends=("python-"{mock,pycountry,pytest})
+makedepends=('git' "python-"{setuptools,sphinx})
 optdepends=('ffmpeg: Required to play streams that are made up of separate audio and video streams, eg. YouTube 1080p+'
             'python-librtmp: Required by the ustreamtv plugin to be able to use non-mobile streams.')
 provides=('streamlink')

aura >>= Determining dependencies...
aura >>= Would you like to edit the PKGBUILD of `streamlink-git`? [Y/n] n
aura >>= Dependency checking failed for these reasons:
The dependency `python-` could not be found. You may need to search for a package to satisfy it.
````

Is this problem with the package itself or AURA? I think it could be AURA.

### LINKED ISSUE #456: Memory leak building purple-matrix-git package
When updating a purple-matrix-git package with the "aura -Akuax --builduser=someuser" command, the output stops at the "determining dependencies..." stage, while the memory usage progressively increases until the system runs out of it (almost 6 GB of free memory + some swap storage is available). The package builds fine manually, and this problem was present with older versions of aura, too, as well as the most recent one.

### PR DESCRIPTION
**Pull request by theotherjimmy**
- [x] Remove bash parsing from AUR dep handling
- [x] Stop parsing unicode needlessly ~(store PKGBUILDs as ByteString)~

Fixes:
Resolves #456 
Resolves #433 
Resolves #427 
Resolves #410 
Resolves #398 
Resolves #392 
Resolves #391 
Resolves #340

### CODE REVIEW

**Comment by theotherjimmy** [comment]
It's not pretty, but it works:
```
jimmy:/home/jimmy/src/aura# sudo /home/jimmy/src/aura/.stack-work/install/x86_64-linux-ncurses6-nopie/lts-8.13/8.0.2/bin/aura -Ai jhbuild
Repository  : aur
Name        : jhbuild
Version     : 3.15.92+1416+ge4528807-2
AUR Status  : Up to Date
Maintainer  : rafaelff
Project URL : https://wiki.gnome.org/Projects/Jhbuild
AUR URL     : https://aur.archlinux.org/packages/jhbuild
License     : GPL
Depends On  : python2 git anthy argyllcms caribou check cmake cups docbook-sgml docbook-utils docbook-xsl dotconf doxygen espeak exempi fwupdate gmime gperf gtkspell3 hyphen intltool itstool kyotocabinet libatasmart libcanberra libdmapsharing libdvdread libgexiv2 libgphoto2 libhangul libical libmusicbrainz5 libndp liboauth libpwquality libraw libunwind libvirt libvpx llvm mpc ninja openldap opus plymouth poppler-glib ppp python-cairo python-pillow ragel ruby sane smbclient source-highlight startup-notification taglib udisks2 usbredir v4l-utils vala valgrind wavpack wget wireless_tools xf86-input-wacom xmlto xorg-server-xwayland xorg-util-macros xtrans
Build Deps  : yelp-tools
Votes       : 12
Popularity  : 0.16
Description : Tool to build the whole GNOME desktop from sources

jimmy:/home/jimmy/src/aura# aura -Ai jhbuild
Repository  : aur
Name        : jhbuild
Version     : 3.15.92+1416+ge4528807-2
AUR Status  : Up to Date
Maintainer  : rafaelff
Project URL : https://wiki.gnome.org/Projects/Jhbuild
AUR URL     : https://aur.archlinux.org/packages/jhbuild
License     : GPL
Depends On  : python2 git
Build Deps  : yelp-tools
Votes       : 12
Popularity  : 0.16
Description : Tool to build the whole GNOME desktop from sources
```

**Comment by theotherjimmy** [comment]
Not done yet though:
```
jimmy:/home/jimmy/src/aura# sudo aura -A jhbuild
aura >>= Determining dependencies...
aura >>= Repository dependencies:
yelp-tools

aura >>= AUR Packages:
jhbuild

aura >>= Continue? [Y/n] 
resolving dependencies...
looking for conflicting packages...

Packages (3) itstool-2.0.2+5+g676f3f7-2  yelp-xsl-3.20.1-2  yelp-tools-3.18.0+1+g193c2bd-1

Total Download Size:   0.26 MiB
Total Installed Size:  1.70 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 yelp-xsl-3.20.1-2-any                                      232.8 KiB   699K/s 00:00 [#################################################] 100%
 itstool-2.0.2+5+g676f3f7-2-any                              18.1 KiB  0.00B/s 00:00 [#################################################] 100%
 yelp-tools-3.18.0+1+g193c2bd-1-any                          19.7 KiB  0.00B/s 00:00 [#################################################] 100%
(3/3) checking keys in keyring                                                       [#################################################] 100%
(3/3) checking package integrity                                                     [#################################################] 100%
(3/3) loading package files                                                          [#################################################] 100%
(3/3) checking for file conflicts                                                    [#################################################] 100%
(3/3) checking available disk space                                                  [#################################################] 100%
:: Processing package changes...
(1/3) installing yelp-xsl                                                            [#################################################] 100%
(2/3) installing itstool                                                             [#################################################] 100%
(3/3) installing yelp-tools                                                          [#################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
aura >>= Building `jhbuild`...
aura >>= Well, building `jhbuild` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Making package: jhbuild 3.15.92+1416+ge4528807-2 (Fri Sep  8 11:56:08 CDT 2017)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> anthy
  -> argyllcms
  -> caribou
  -> check
  -> cups
  -> docbook-sgml
  -> docbook-utils
  -> docbook-xsl
  -> dotconf
  -> doxygen
  -> exempi
  -> fwupdate
  -> gmime
  -> gperf
  -> gtkspell3
  -> intltool
  -> kyotocabinet
  -> libatasmart
  -> libcanberra
  -> libdmapsharing
  -> libgexiv2
  -> libgphoto2
  -> libhangul
  -> libical
  -> libmusicbrainz5
  -> libndp
  -> liboauth
  -> libpwquality
  -> libraw
  -> libvirt
  -> llvm
  -> mpc
  -> ninja
  -> openldap
  -> plymouth
  -> poppler-glib
  -> ppp
  -> python-cairo
  -> python-pillow
  -> ragel
  -> sane
  -> source-highlight
  -> udisks2
  -> vala
  -> valgrind
  -> xf86-input-wacom
  -> xmlto
  -> xtrans
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
==> ERROR: An unknown error has occurred. Exiting...



aura >>= Would you like to continue anyway? [Y/n] n
aura >>= Building failed.
jimmy:/home/jimmy/src/aura# sudo /home/jimmy/src/aura/.stack-work/install/x86_64-linux-ncurses6-nopie/lts-8.13/8.0.2/bin/aura -A jhbuild
aura >>= Determining dependencies...
aura: fd:7: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by theotherjimmy** [comment]
```
jimmy:/home/jimmy/src/aura# sudo /home/jimmy/src/aura/.stack-work/install/x86_64-linux-ncurses6-nopie/lts-8.13/8.0.2/bin/aura -A jhbuild
aura >>= Determining dependencies...
aura >>= Repository dependencies:
anthy
argyllcms
caribou
check
cups
docbook-sgml
docbook-utils
docbook-xsl
dotconf
doxygen
exempi
fwupdate
gmime
gperf
gtkspell3
intltool
kyotocabinet
libatasmart
libcanberra
libdmapsharing
libgexiv2
libgphoto2
libhangul
libical
libmusicbrainz5
libndp
liboauth
libpwquality
libraw
libvirt
llvm
mpc
ninja
openldap
poppler-glib
ppp
python-cairo
python-pillow
ragel
sane
source-highlight
udisks2
vala
valgrind
xf86-input-wacom
xmlto
xtrans

aura >>= AUR Packages:
jhbuild
plymouth

aura >>= Continue? [Y/n] y
```

IT WORKS!

**Comment by theotherjimmy** [comment]
@fosskers Take a look please.

**Comment by theotherjimmy** [comment]
It does aur queries at a blazing 3-7KB/s

**Comment by fosskers** [comment]
Ho! Hot damn!

Unfortunately I'm going on vacation in a few days. I'll be back in two weeks where I can give this a proper review. Is that okay?

**Comment by theotherjimmy** [comment]
How about we get @bb010g to review instead then?

**Comment by fosskers** [comment]
Sure, I trust his judgement.

I took a quick look at it after all - this isn't involving `.SRCINFO` yet eh (which is the dream).

**Comment by theotherjimmy** [comment]
No, I expect that will be easier after switching to libgit. This actually used the aur rest api. The surprising bit is that it's not super slow, despite being completely serial.

**Comment by theotherjimmy** [comment]
@bb010g Could you review when you get a chance?

**Comment by fosskers** [comment]
I'm back from vacation now.

**Comment by theotherjimmy** [comment]
I hope you had a relaxing vacation. I take it you mentioned that as you are about to review?

**Comment by fosskers** [comment]
Not right this minute (I'm starting my work day), but yeah.

**Comment by bb010g** [comment]
Sorry for not having the time to review this; my schedule's been weird lately.

**Comment by fosskers** [comment]
Not a problem, that's life eh.

**Pull request merged**
